name: build-frontend-web
on:
  push:
    paths:
      - "frontend/web/**"
      - ".github/workflows/build-frontend-web.yaml"
jobs:
  build:
    name: Build ocr-chinese
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build production
        run: yarn build

  publish:
    name: Publish Image
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: frontend/web
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Push images
        run: |
          # Setup credentials for GitHub packages
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u antonve --password-stdin
          # Push images
          IMAGE_NAME=ghcr.io/antonve/language-learning-tools/frontend-web
          docker build --no-cache -t $IMAGE_NAME:latest .
          docker tag $IMAGE_NAME:latest $IMAGE_NAME:$GITHUB_SHA
          docker push $IMAGE_NAME
